### ISSUE TITLE
Add support for another languages

### ISSUE THREAD

**Issue by cacu100** [innir/gtranscribe#10]
The software looks nice. But I need a transcription from Spanish audio :)  Is possible add support for another languages. can I contribute with this requirement?

**Comment by innir** [comment]
You can transcribe audio of any language with this software. Load the audio file, listen to the voice and start typing...
For spell-checking you need to install the dictionary for the language you are transcribing.

**Comment by innir** [comment]
Closing it now as it's no bug.
