### ISSUE TITLE
Close button in about is defunct

### ISSUE THREAD

**Issue by stefanct** [innir/gtranscribe#11]
Closing die dialog via escape key and window title (X) works fine.

**Comment by innir** [comment]
There is no close button in the about dialog:
![grafik](https://user-images.githubusercontent.com/5419701/60192843-e50cfb80-9836-11e9-875f-4237059dbe88.png)

What am I missing here?

**Comment by stefanct** [comment]
Funny. This must be one of these cool Gnome features that eases the life of everybody... ;)

This is Debian's version (0.7.1-2 from stretch/stable) on Mate:
![image](https://user-images.githubusercontent.com/457881/60211894-59a86000-9860-11e9-9fca-c9381da44b17.png)
I haven't tried compiling it from source but I would not expect any change.

**Comment by innir** [comment]
Well, looking at the code (https://github.com/innir/gtranscribe/blob/master/bin/gtranscribe#L182-L194)
there is nothing about a close button. I just can't make something work that doesn't exist in the code.

Also, the documentation does not reference any close function: https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html

I think it's actually Mate that's doing something strange here, not Gnome.

**Comment by innir** [comment]
Could you edit `/usr/bin/gtranscribe` and add

`        about_dialog.set_default_response(Gtk.ResponseType.CLOSE)
`
Before line 194 (https://github.com/innir/gtranscribe/blob/master/bin/gtranscribe#L194) maybe that helps.

**Comment by stefanct** [comment]
Nope, but the solution from [here](https://stackoverflow.com/questions/7385817/close-button-in-pygtk-about-dialog-not-closing-dialog) works:

        about_dialog.run()
        about_dialog.hide()

instead of

        about_dialog.show()

The documentation does mention a close button btw (and the run() function) but does a poor job explaining the behavior. I now feel a bit sorry that I brought up such a stupid thing... but OTOH we came up with a solution(?) eventually, cheers :)

**Comment by innir** [comment]
No need to feel sorry - happy there was an easy solution.
