### ISSUE TITLE
pause/play when pause/play multimedia key is pressed

### ISSUE THREAD

**Issue by pabs3** [innir/gtranscribe#13]
A useful feature addition would be to make pressing the pause/play multimedia key on the keyboard trigger the pause/play button in gTranscribe. Other transcribe tools like Parlatype support this feature.

**Comment by innir** [comment]
Yes, it was working once but I don't get it working again :-( The relevant ode section is https://github.com/innir/gtranscribe/blob/master/bin/gtranscribe#L82-L94.
