### ISSUE TITLE
traceback and silent failure to open mp3 files

### ISSUE THREAD

**Issue by pabs3** [innir/gtranscribe#15]
When I try to open an mp3 file, I get the following traceback and gtranscribe silently fails to open the mp3 file. I cannot play the mp3 file and the title of the window does not change.

```
Traceback (most recent call last):
  File "/usr/bin/gtranscribe", line 234, in update_file
    duration = ns_to_time(self.player.duration)
  File "/usr/lib/python3/dist-packages/gtranscribe/helpers.py", line 55, in ns_to_time
    return datetime.time(h, m, s, ms)
ValueError: hour must be in 0..23
```

**Comment by innir** [comment]
Uh strange, is it a very long mp3 - like longer than 24 hours?

**Comment by pabs3** [comment]
It happens with every file I try, but for example for one of them
ffprobe says it is 00:05:27.87 in length.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by innir** [comment]
Well, some of my mp3 files have the same problem, GStreamer can't get their duration. I have no idea why but will investigate further. Anyway, I fixed the traceback with d8be2b6.

**Comment by innir** [comment]
I'm not very happy with the solution but it's a workaround. Just play the file and it will (hopefully) be able to query the duration after some seconds.

**Comment by pabs3** [comment]
That seems like a reasonable workaround to me, thanks for that.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
