### ISSUE TITLE
Audio files longer than 24h are not working

### ISSUE THREAD

**Issue by samwilson** [innir/gtranscribe#17]
I seem to be unable to open any MP3 file (with version 0.7.1). The following error results:

```
(gtranscribe:94948): IBUS-WARNING **: 18:38:55.696: Unable to connect to ibus: Could not connect: Connection refused
/usr/bin/gtranscribe:202: DeprecationWarning: Gtk.ToggleAction.set_active is deprecated
  self.play_action.set_active(False)
/usr/bin/gtranscribe:211: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  GObject.idle_add(self.update_file, audiofile)
Traceback (most recent call last):
  File "/usr/bin/gtranscribe", line 224, in update_file
    duration = ns_to_time(self.player.duration)
  File "/usr/lib/python3/dist-packages/gtranscribe/helpers.py", line 57, in ns_to_time
    return datetime.time(h, m, s, ms)
ValueError: hour must be in 0..23
/usr/bin/gtranscribe:358: DeprecationWarning: This method will be removed in a future version of Python. Use 'locale.format_string()' instead.
  return u'%s\xd7' % locale.format('%.1f', value)
```

Sorry I don't have more information!

**Comment by innir** [comment]
Could you please try to reproduce with the current version (0.10)? The version you are using is four years old.

**Comment by innir** [comment]
Well, I spotted the real error now - I guess you are using an audio file that is longer than 24h. I'll fix that.
As a workaround you could cut you audio file in shorter pieces.

**Comment by samwilson** [comment]
Thanks!

Sorry I didn't realise I was so out of date (I'd installed https://packages.ubuntu.com/bionic/gtranscribe ).

**Comment by innir** [comment]
No problem. I uploaded a package of the new version, could you try it: https://github.com/innir/gtranscribe/releases/download/0.10.1/gtranscribe_0.10.1-1_all.deb (there is also a gpg signature in the download section to verify integrity)
