### ISSUE TITLE
Need undo

### ISSUE THREAD

**Issue by livier** [innir/gtranscribe#19]
I use Gtranscribe since a few weeks but I just made an error that cost too muche loss of work : 
I wanted to Write "A" CAPS-A and my finger touched CTRL instead off CAPS and ... all was selected, then the next letter erased all the text I already made. My error off course, but I lost too much. Undo should have save me. 
Sadly, i need another tool

**Comment by innir** [comment]
Sorry to hear that ... I added an undo function now - could you please test?

**Comment by livier** [comment]
Very fast solution, thanks a lot ... but ... 
I never compiled anything and I do not know how to test that on ubuntu .
Package not yet available for update of course. 
May I have to (learm how to )compil 
May I can download  a deb file, and install it (and what about the next updates ?) 
Sorry for my newbie question

**Comment by innir** [comment]
No worries, please try to install the attached .deb (you need to unzip it first)
[gtranscribe_0.10.2-1_all.deb.zip](https://github.com/innir/gtranscribe/files/10339257/gtranscribe_0.10.2-1_all.deb.zip)

**Comment by livier** [comment]
Undo (CTRL Z)  seems to work now. What a usefull feature ;-)
If I need normal updates now, I understand I will need uninstall your deb and install it as usual when your update will be on Ubuntu's repos. Wright ? 
Thanks and happy new Year, if the sky does not fall on our heads :-)

**Comment by innir** [comment]
Great :-) No, you don't have to uninstall anything - once the Ubuntu repository gets the update you will receive it automatically.

**Comment by livier** [comment]
I uninstalled repo,s version before installing yours, I should not have to do that ?
