### ISSUE TITLE
looking for glade file in the wrong place

### ISSUE THREAD

**Issue by anarcat** [innir/gtranscribe#4]
I cloned the repo, ran setup.py install, and ran the program.

It tried to find the `.glade` file in `/usr/share` instead of `/usr/local/share`. I made a symlink to fix the problem, but it seems there's an issue with the setup there...

```
lrwxrwxrwx 1 root root 49 mar 15 09:51 /usr/share/gTranscribe/ui/gTranscribe.glade -> /usr/local/share/gTranscribe/ui/gTranscribe.glade
```

**Comment by innir** [comment]
I see that too, still don't know why as I use "sys.prefix" to determine the path which is the recommended way to do it.

**Comment by innir** [comment]
Could you post the output of `./setup.py --dry-run install`? For me the output is correct, so `*.glade` are installed in `/usr/local/share`
