### ISSUE TITLE
Rewinding / Forwarding restarts playback

### ISSUE THREAD

**Issue by lassegs** [innir/gtranscribe#5]
Pressing CTRL+Left for rewinding has to be done very carefully, because pressing it for too long will make it restart playback from beginning. CTRL+Right doesn't really work so well.  And both of these hotkeys block normal usage to jump between words.

**Comment by innir** [comment]
Strange, for me it's fixed since commit f8a6877. Do you really use the latest version?

Regarding CTRL+[Left, Right] oh yes this is really not optimal, I'll consider changing it.

**Comment by lassegs** [comment]
Sorry, updated, that is indeed fixed now. Really like this application, thanks a lot. But yeah, moving around in text with CTRL+[Left+Right] is very useful to me. How about a way of remapping them?

**Comment by innir** [comment]
Changed the key bindings now, hope it helps.
