### ISSUE TITLE
saving text file should ask before overriding

### ISSUE THREAD

**Issue by drzraf** [innir/gtranscribe#7]
When saving the first time, there is no confirmation of overwriting.
I just erased an audio file for misclicking in the file explorer.
(and then I could not change the output file anymore (no "save as" button))

BTW: great software

**Comment by innir** [comment]
Oh, sorry you lost your audio file :-(
I thought the overwrite warning was the default, seems not to be the cage - I'll fix it in a minute.
Great that you like the software :-)

**Comment by drzraf** [comment]
(I had a backup)
thanks for the fix!
